version: "3"
services:
  mysql:
    image: "mysql:8.2"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=main
    networks:
      - app
networks:
  app: